import { PhonicsCategory, HFWSet } from './types';

export const PHONICS_DATA: PhonicsCategory[] = [
  {
    id: 'set_1',
    name: 'Set 1: s / a / t / p / i / n',
    skills: [
      { id: 'sat', label: 'sat', category: 'set_1' },
      { id: 'pin', label: 'pin', category: 'set_1' },
      { id: 'pat', label: 'pat', category: 'set_1' },
      { id: 'tap', label: 'tap', category: 'set_1' },
      { id: 'sip', label: 'sip', category: 'set_1' },
      { id: 'tip', label: 'tip', category: 'set_1' },
      { id: 'nap', label: 'nap', category: 'set_1' },
      { id: 'ant', label: 'ant', category: 'set_1' },
      { id: 'tan', label: 'tan', category: 'set_1' },
      { id: 'pan', label: 'pan', category: 'set_1' },
      { id: 'pit', label: 'pit', category: 'set_1' },
      { id: 'sit', label: 'sit', category: 'set_1' },
      { id: 'sap', label: 'sap', category: 'set_1' },
      { id: 'snap', label: 'snap', category: 'set_1' },
      { id: 'spin', label: 'spin', category: 'set_1' },
      { id: 'spit', label: 'spit', category: 'set_1' },
      { id: 'past', label: 'past', category: 'set_1' },
      { id: 'pats', label: 'pats', category: 'set_1' },
      { id: 'taps', label: 'taps', category: 'set_1' },
      { id: 'pants', label: 'pants', category: 'set_1' },
    ]
  },
  {
    id: 'set_2',
    name: 'Set 2: m / d / g / o / c / f',
    skills: [
      { id: 'map', label: 'map', category: 'set_2' },
      { id: 'mat', label: 'mat', category: 'set_2' },
      { id: 'dam', label: 'dam', category: 'set_2' },
      { id: 'dip', label: 'dip', category: 'set_2' },
      { id: 'dig', label: 'dig', category: 'set_2' },
      { id: 'dot', label: 'dot', category: 'set_2' },
      { id: 'dog', label: 'dog', category: 'set_2' },
      { id: 'cat', label: 'cat', category: 'set_2' },
      { id: 'fog', label: 'fog', category: 'set_2' },
      { id: 'fig', label: 'fig', category: 'set_2' },
      { id: 'fan', label: 'fan', category: 'set_2' },
      { id: 'fit', label: 'fit', category: 'set_2' },
      { id: 'fin', label: 'fin', category: 'set_2' },
      { id: 'mad', label: 'mad', category: 'set_2' },
      { id: 'pad', label: 'pad', category: 'set_2' },
      { id: 'man', label: 'man', category: 'set_2' },
      { id: 'tin', label: 'tin', category: 'set_2' },
      { id: 'dim', label: 'dim', category: 'set_2' },
      { id: 'cod', label: 'cod', category: 'set_2' },
      { id: 'pot', label: 'pot', category: 'set_2' },
    ]
  },
  {
    id: 'set_3',
    name: 'Set 3: k / e / r / u',
    skills: [
      { id: 'pen', label: 'pen', category: 'set_3' },
      { id: 'ten', label: 'ten', category: 'set_3' },
      { id: 'net', label: 'net', category: 'set_3' },
      { id: 'men', label: 'men', category: 'set_3' },
      { id: 'red', label: 'red', category: 'set_3' },
      { id: 'set', label: 'set', category: 'set_3' },
      { id: 'pet', label: 'pet', category: 'set_3' },
      { id: 'sun', label: 'sun', category: 'set_3' },
      { id: 'run', label: 'run', category: 'set_3' },
      { id: 'fun', label: 'fun', category: 'set_3' },
      { id: 'rat', label: 'rat', category: 'set_3' },
      { id: 'kit', label: 'kit', category: 'set_3' },
      { id: 'rip', label: 'rip', category: 'set_3' },
    ]
  },
  {
    id: 'set_4',
    name: 'Set 4: b / h / l',
    skills: [
      { id: 'bat', label: 'bat', category: 'set_4' },
      { id: 'hat', label: 'hat', category: 'set_4' },
      { id: 'lap', label: 'lap', category: 'set_4' },
      { id: 'help', label: 'help', category: 'set_4' },
      { id: 'lip', label: 'lip', category: 'set_4' },
      { id: 'hit', label: 'hit', category: 'set_4' },
      { id: 'tab', label: 'tab', category: 'set_4' },
      { id: 'bit', label: 'bit', category: 'set_4' },
      { id: 'lit', label: 'lit', category: 'set_4' },
      { id: 'plan', label: 'plan', category: 'set_4' },
      { id: 'slap', label: 'slap', category: 'set_4' },
      { id: 'flat', label: 'flat', category: 'set_4' },
      { id: 'split', label: 'split', category: 'set_4' },
    ]
  },
  {
    id: 'set_5',
    name: 'Set 5: j / w / v',
    skills: [
      { id: 'win', label: 'win', category: 'set_5' },
      { id: 'wet', label: 'wet', category: 'set_5' },
      { id: 'jet', label: 'jet', category: 'set_5' },
      { id: 'wag', label: 'wag', category: 'set_5' },
      { id: 'jam', label: 'jam', category: 'set_5' },
      { id: 'jaw', label: 'jaw', category: 'set_5' },
      { id: 'jog', label: 'jog', category: 'set_5' },
      { id: 'jar', label: 'jar', category: 'set_5' },
      { id: 'vet', label: 'vet', category: 'set_5' },
      { id: 'van', label: 'van', category: 'set_5' },
      { id: 'web', label: 'web', category: 'set_5' },
      { id: 'vent', label: 'vent', category: 'set_5' },
      { id: 'west', label: 'west', category: 'set_5' },
      { id: 'wave', label: 'wave', category: 'set_5' },
      { id: 'wax', label: 'wax', category: 'set_5' },
      { id: 'view', label: 'view', category: 'set_5' },
      { id: 'war', label: 'war', category: 'set_5' },
      { id: 'vow', label: 'vow', category: 'set_5' },
      { id: 'wit', label: 'wit', category: 'set_5' },
      { id: 'jammed', label: 'jammed', category: 'set_5' },
    ]
  },
  {
    id: 'set_6',
    name: 'Set 6: y / z',
    skills: [
      { id: 'yes', label: 'yes', category: 'set_6' },
      { id: 'yet', label: 'yet', category: 'set_6' },
      { id: 'say', label: 'say', category: 'set_6' },
      { id: 'pay', label: 'pay', category: 'set_6' },
      { id: 'way', label: 'way', category: 'set_6' },
      { id: 'zap', label: 'zap', category: 'set_6' },
      { id: 'zip', label: 'zip', category: 'set_6' },
      { id: 'yay', label: 'yay', category: 'set_6' },
      { id: 'toy', label: 'toy', category: 'set_6' },
      { id: 'zoo', label: 'zoo', category: 'set_6' },
      { id: 'lazy', label: 'lazy', category: 'set_6' },
      { id: 'cozy', label: 'cozy', category: 'set_6' },
      { id: 'spy', label: 'spy', category: 'set_6' },
      { id: 'stay', label: 'stay', category: 'set_6' },
      { id: 'play', label: 'play', category: 'set_6' },
      { id: 'day', label: 'day', category: 'set_6' },
      { id: 'guy', label: 'guy', category: 'set_6' },
      { id: 'ray', label: 'ray', category: 'set_6' },
      { id: 'lay', label: 'lay', category: 'set_6' },
    ]
  },
  {
    id: 'set_7',
    name: 'Set 7: x / qu',
    skills: [
      { id: 'six', label: 'six', category: 'set_7' },
      { id: 'mix', label: 'mix', category: 'set_7' },
      { id: 'fix', label: 'fix', category: 'set_7' },
      { id: 'box', label: 'box', category: 'set_7' },
      { id: 'fox', label: 'fox', category: 'set_7' },
      { id: 'tax', label: 'tax', category: 'set_7' },
      { id: 'max', label: 'max', category: 'set_7' },
      { id: 'next', label: 'next', category: 'set_7' },
      { id: 'exit', label: 'exit', category: 'set_7' },
      { id: 'quiz', label: 'quiz', category: 'set_7' },
      { id: 'quick', label: 'quick', category: 'set_7' },
      { id: 'quack', label: 'quack', category: 'set_7' },
      { id: 'quest', label: 'quest', category: 'set_7' },
      { id: 'quiet', label: 'quiet', category: 'set_7' },
      { id: 'quilt', label: 'quilt', category: 'set_7' },
      { id: 'taxi', label: 'taxi', category: 'set_7' },
      { id: 'lax', label: 'lax', category: 'set_7' },
      { id: 'vex', label: 'vex', category: 'set_7' },
      { id: 'flex', label: 'flex', category: 'set_7' },
    ]
  },
  {
    id: 'set_8',
    name: 'Set 8: ck / th / wh',
    skills: [
      { id: 'back', label: 'back', category: 'set_8' },
      { id: 'sack', label: 'sack', category: 'set_8' },
      { id: 'pack', label: 'pack', category: 'set_8' },
      { id: 'thick', label: 'thick', category: 'set_8' },
      { id: 'thin', label: 'thin', category: 'set_8' },
      { id: 'that', label: 'that', category: 'set_8' },
      { id: 'them', label: 'them', category: 'set_8' },
      { id: 'then', label: 'then', category: 'set_8' },
      { id: 'this', label: 'this', category: 'set_8' },
      { id: 'wham', label: 'wham', category: 'set_8' },
      { id: 'whiz', label: 'whiz', category: 'set_8' },
      { id: 'whit', label: 'whit', category: 'set_8' },
      { id: 'whisk', label: 'whisk', category: 'set_8' },
      { id: 'whip', label: 'whip', category: 'set_8' },
      { id: 'when', label: 'when', category: 'set_8' },
      { id: 'which', label: 'which', category: 'set_8' },
      { id: 'whack', label: 'whack', category: 'set_8' },
      { id: 'with', label: 'with', category: 'set_8' },
      { id: 'math', label: 'math', category: 'set_8' },
      { id: 'bath', label: 'bath', category: 'set_8' },
    ]
  },
  {
    id: 'set_9',
    name: 'Set 9: ll / ss / ff / zz',
    skills: [
      { id: 'hill', label: 'hill', category: 'set_9' },
      { id: 'fill', label: 'fill', category: 'set_9' },
      { id: 'bill', label: 'bill', category: 'set_9' },
      { id: 'tell', label: 'tell', category: 'set_9' },
      { id: 'sell', label: 'sell', category: 'set_9' },
      { id: 'miss', label: 'miss', category: 'set_9' },
      { id: 'kiss', label: 'kiss', category: 'set_9' },
      { id: 'hiss', label: 'hiss', category: 'set_9' },
      { id: 'pass', label: 'pass', category: 'set_9' },
      { id: 'class', label: 'class', category: 'set_9' },
      { id: 'boss', label: 'boss', category: 'set_9' },
      { id: 'off', label: 'off', category: 'set_9' },
      { id: 'sniff', label: 'sniff', category: 'set_9' },
      { id: 'staff', label: 'staff', category: 'set_9' },
      { id: 'cliff', label: 'cliff', category: 'set_9' },
      { id: 'fuzz', label: 'fuzz', category: 'set_9' },
      { id: 'jazz', label: 'jazz', category: 'set_9' },
      { id: 'buzz', label: 'buzz', category: 'set_9' },
      { id: 'shell', label: 'shell', category: 'set_9' },
    ]
  },
  {
    id: 'set_10',
    name: 'Set 10: ch / sh / ng',
    skills: [
      { id: 'chat', label: 'chat', category: 'set_10' },
      { id: 'chip', label: 'chip', category: 'set_10' },
      { id: 'chin', label: 'chin', category: 'set_10' },
      { id: 'chop', label: 'chop', category: 'set_10' },
      { id: 'much', label: 'much', category: 'set_10' },
      { id: 'such', label: 'such', category: 'set_10' },
      { id: 'rich', label: 'rich', category: 'set_10' },
      { id: 'ship', label: 'ship', category: 'set_10' },
      { id: 'shop', label: 'shop', category: 'set_10' },
      { id: 'shut', label: 'shut', category: 'set_10' },
      { id: 'fish', label: 'fish', category: 'set_10' },
      { id: 'dish', label: 'dish', category: 'set_10' },
      { id: 'wish', label: 'wish', category: 'set_10' },
      { id: 'mash', label: 'mash', category: 'set_10' },
      { id: 'cash', label: 'cash', category: 'set_10' },
      { id: 'ring', label: 'ring', category: 'set_10' },
      { id: 'sing', label: 'sing', category: 'set_10' },
      { id: 'wing', label: 'wing', category: 'set_10' },
      { id: 'bang', label: 'bang', category: 'set_10' },
      { id: 'song', label: 'song', category: 'set_10' },
    ]
  },
  {
    id: 'set_11',
    name: 'Set 11: CCVC (Consonant Clusters)',
    skills: [
      { id: 'trip', label: 'trip', category: 'set_11' },
      { id: 'trap', label: 'trap', category: 'set_11' },
      { id: 'trim', label: 'trim', category: 'set_11' },
      { id: 'frog', label: 'frog', category: 'set_11' },
      { id: 'flag', label: 'flag', category: 'set_11' },
      { id: 'flip', label: 'flip', category: 'set_11' },
      { id: 'grab', label: 'grab', category: 'set_11' },
      { id: 'grin', label: 'grin', category: 'set_11' },
      { id: 'grip', label: 'grip', category: 'set_11' },
      { id: 'snap', label: 'snap', category: 'set_11' },
      { id: 'snip', label: 'snip', category: 'set_11' },
      { id: 'stop', label: 'stop', category: 'set_11' },
      { id: 'step', label: 'step', category: 'set_11' },
      { id: 'skip', label: 'skip', category: 'set_11' },
      { id: 'skin', label: 'skin', category: 'set_11' },
      { id: 'slip', label: 'slip', category: 'set_11' },
      { id: 'clip', label: 'clip', category: 'set_11' },
      { id: 'plum', label: 'plum', category: 'set_11' },
    ]
  },
  {
    id: 'set_12',
    name: 'Set 12: CVCC (Final Consonant Clusters)',
    skills: [
      { id: 'band', label: 'band', category: 'set_12' },
      { id: 'hand', label: 'hand', category: 'set_12' },
      { id: 'sand', label: 'sand', category: 'set_12' },
      { id: 'land', label: 'land', category: 'set_12' },
      { id: 'send', label: 'send', category: 'set_12' },
      { id: 'bend', label: 'bend', category: 'set_12' },
      { id: 'pond', label: 'pond', category: 'set_12' },
      { id: 'wind', label: 'wind', category: 'set_12' },
      { id: 'milk', label: 'milk', category: 'set_12' },
      { id: 'silk', label: 'silk', category: 'set_12' },
      { id: 'mask', label: 'mask', category: 'set_12' },
      { id: 'task', label: 'task', category: 'set_12' },
      { id: 'jump', label: 'jump', category: 'set_12' },
      { id: 'lump', label: 'lump', category: 'set_12' },
      { id: 'tent', label: 'tent', category: 'set_12' },
      { id: 'damp', label: 'damp', category: 'set_12' },
      { id: 'hint', label: 'hint', category: 'set_12' },
      { id: 'sink', label: 'sink', category: 'set_12' },
      { id: 'bank', label: 'bank', category: 'set_12' },
      { id: 'lamp', label: 'lamp', category: 'set_12' },
    ]
  },
  {
    id: 'set_13',
    name: 'Set 13: CCVCC (Complex Clusters)',
    skills: [
      { id: 'plant', label: 'plant', category: 'set_13' },
      { id: 'print', label: 'print', category: 'set_13' },
      { id: 'crust', label: 'crust', category: 'set_13' },
      { id: 'blend', label: 'blend', category: 'set_13' },
      { id: 'grand', label: 'grand', category: 'set_13' },
      { id: 'stand', label: 'stand', category: 'set_13' },
      { id: 'stamp', label: 'stamp', category: 'set_13' },
      { id: 'clamp', label: 'clamp', category: 'set_13' },
      { id: 'grasp', label: 'grasp', category: 'set_13' },
      { id: 'trend', label: 'trend', category: 'set_13' },
      { id: 'brand', label: 'brand', category: 'set_13' },
      { id: 'drink', label: 'drink', category: 'set_13' },
      { id: 'trunk', label: 'trunk', category: 'set_13' },
      { id: 'plump', label: 'plump', category: 'set_13' },
      { id: 'grump', label: 'grump', category: 'set_13' },
      { id: 'slept', label: 'slept', category: 'set_13' },
      { id: 'crept', label: 'crept', category: 'set_13' },
      { id: 'twist', label: 'twist', category: 'set_13' },
      { id: 'trust', label: 'trust', category: 'set_13' },
    ]
  },
  {
    id: 'set_14',
    name: 'Set 14: ay / ai / a_e (Long A)',
    skills: [
      { id: 'play', label: 'play', category: 'set_14' },
      { id: 'day', label: 'day', category: 'set_14' },
      { id: 'say', label: 'say', category: 'set_14' },
      { id: 'may', label: 'may', category: 'set_14' },
      { id: 'tray', label: 'tray', category: 'set_14' },
      { id: 'rain', label: 'rain', category: 'set_14' },
      { id: 'pain', label: 'pain', category: 'set_14' },
      { id: 'main', label: 'main', category: 'set_14' },
      { id: 'train', label: 'train', category: 'set_14' },
      { id: 'tail', label: 'tail', category: 'set_14' },
      { id: 'mail', label: 'mail', category: 'set_14' },
      { id: 'sail', label: 'sail', category: 'set_14' },
      { id: 'wait', label: 'wait', category: 'set_14' },
      { id: 'paid', label: 'paid', category: 'set_14' },
      { id: 'chain', label: 'chain', category: 'set_14' },
      { id: 'cake', label: 'cake', category: 'set_14' },
      { id: 'make', label: 'make', category: 'set_14' },
      { id: 'bake', label: 'bake', category: 'set_14' },
      { id: 'gate', label: 'gate', category: 'set_14' },
      { id: 'name', label: 'name', category: 'set_14' },
    ]
  },
  {
    id: 'set_15',
    name: 'Set 15: ee / ea / ie / e_e (Long E)',
    skills: [
      { id: 'see', label: 'see', category: 'set_15' },
      { id: 'tree', label: 'tree', category: 'set_15' },
      { id: 'green', label: 'green', category: 'set_15' },
      { id: 'queen', label: 'queen', category: 'set_15' },
      { id: 'sleep', label: 'sleep', category: 'set_15' },
      { id: 'sheep', label: 'sheep', category: 'set_15' },
      { id: 'sweet', label: 'sweet', category: 'set_15' },
      { id: 'eat', label: 'eat', category: 'set_15' },
      { id: 'sea', label: 'sea', category: 'set_15' },
      { id: 'team', label: 'team', category: 'set_15' },
      { id: 'dream', label: 'dream', category: 'set_15' },
      { id: 'clean', label: 'clean', category: 'set_15' },
      { id: 'each', label: 'each', category: 'set_15' },
      { id: 'reach', label: 'reach', category: 'set_15' },
      { id: 'piece', label: 'piece', category: 'set_15' },
      { id: 'chief', label: 'chief', category: 'set_15' },
      { id: 'these', label: 'these', category: 'set_15' },
      { id: 'theme', label: 'theme', category: 'set_15' },
      { id: 'eve', label: 'eve', category: 'set_15' },
      { id: 'pete', label: 'Pete', category: 'set_15' },
    ]
  },
  {
    id: 'set_16',
    name: 'Set 16: ie / y / igh / i_e (Long I)',
    skills: [
      { id: 'pie', label: 'pie', category: 'set_16' },
      { id: 'tie', label: 'tie', category: 'set_16' },
      { id: 'cried', label: 'cried', category: 'set_16' },
      { id: 'tried', label: 'tried', category: 'set_16' },
      { id: 'my', label: 'my', category: 'set_16' },
      { id: 'by', label: 'by', category: 'set_16' },
      { id: 'fly', label: 'fly', category: 'set_16' },
      { id: 'dry', label: 'dry', category: 'set_16' },
      { id: 'sky', label: 'sky', category: 'set_16' },
      { id: 'night', label: 'night', category: 'set_16' },
      { id: 'light', label: 'light', category: 'set_16' },
      { id: 'high', label: 'high', category: 'set_16' },
      { id: 'sigh', label: 'sigh', category: 'set_16' },
      { id: 'tight', label: 'tight', category: 'set_16' },
      { id: 'might', label: 'might', category: 'set_16' },
      { id: 'time', label: 'time', category: 'set_16' },
      { id: 'ride', label: 'ride', category: 'set_16' },
      { id: 'bike', label: 'bike', category: 'set_16' },
      { id: 'slide', label: 'slide', category: 'set_16' },
      { id: 'fine', label: 'fine', category: 'set_16' },
    ]
  },
  {
    id: 'set_17',
    name: 'Set 17: oa / ow / o_e (Long O)',
    skills: [
      { id: 'boat', label: 'boat', category: 'set_17' },
      { id: 'coat', label: 'coat', category: 'set_17' },
      { id: 'goat', label: 'goat', category: 'set_17' },
      { id: 'road', label: 'road', category: 'set_17' },
      { id: 'toad', label: 'toad', category: 'set_17' },
      { id: 'snow', label: 'snow', category: 'set_17' },
      { id: 'grow', label: 'grow', category: 'set_17' },
      { id: 'slow', label: 'slow', category: 'set_17' },
      { id: 'show', label: 'show', category: 'set_17' },
      { id: 'blow', label: 'blow', category: 'set_17' },
      { id: 'hope', label: 'hope', category: 'set_17' },
      { id: 'rope', label: 'rope', category: 'set_17' },
      { id: 'note', label: 'note', category: 'set_17' },
      { id: 'bone', label: 'bone', category: 'set_17' },
      { id: 'cone', label: 'cone', category: 'set_17' },
      { id: 'stone', label: 'stone', category: 'set_17' },
      { id: 'home', label: 'home', category: 'set_17' },
      { id: 'those', label: 'those', category: 'set_17' },
      { id: 'rode', label: 'rode', category: 'set_17' },
      { id: 'nose', label: 'nose', category: 'set_17' },
    ]
  },
  {
    id: 'set_18',
    name: 'Set 18: ph / oo (Long OO)',
    skills: [
      { id: 'phone', label: 'phone', category: 'set_18' },
      { id: 'photo', label: 'photo', category: 'set_18' },
      { id: 'elephant', label: 'elephant', category: 'set_18' },
      { id: 'dolphin', label: 'dolphin', category: 'set_18' },
      { id: 'graph', label: 'graph', category: 'set_18' },
      { id: 'alphabet', label: 'alphabet', category: 'set_18' },
      { id: 'trophy', label: 'trophy', category: 'set_18' },
      { id: 'nephew', label: 'nephew', category: 'set_18' },
      { id: 'phantom', label: 'phantom', category: 'set_18' },
      { id: 'sphere', label: 'sphere', category: 'set_18' },
      { id: 'book', label: 'book', category: 'set_18' },
      { id: 'look', label: 'look', category: 'set_18' },
      { id: 'cook', label: 'cook', category: 'set_18' },
      { id: 'took', label: 'took', category: 'set_18' },
      { id: 'foot', label: 'foot', category: 'set_18' },
      { id: 'wood', label: 'wood', category: 'set_18' },
      { id: 'good', label: 'good', category: 'set_18' },
      { id: 'hood', label: 'hood', category: 'set_18' },
      { id: 'shook', label: 'shook', category: 'set_18' },
      { id: 'stood', label: 'stood', category: 'set_18' },
    ]
  },
  {
    id: 'set_19',
    name: 'Set 19: or / ar',
    skills: [
      { id: 'car', label: 'car', category: 'set_19' },
      { id: 'far', label: 'far', category: 'set_19' },
      { id: 'star', label: 'star', category: 'set_19' },
      { id: 'jar', label: 'jar', category: 'set_19' },
      { id: 'bar', label: 'bar', category: 'set_19' },
      { id: 'park', label: 'park', category: 'set_19' },
      { id: 'dark', label: 'dark', category: 'set_19' },
      { id: 'shark', label: 'shark', category: 'set_19' },
      { id: 'hard', label: 'hard', category: 'set_19' },
      { id: 'farm', label: 'farm', category: 'set_19' },
      { id: 'or', label: 'or', category: 'set_19' },
      { id: 'for', label: 'for', category: 'set_19' },
      { id: 'fork', label: 'fork', category: 'set_19' },
      { id: 'born', label: 'born', category: 'set_19' },
      { id: 'corn', label: 'corn', category: 'set_19' },
      { id: 'storm', label: 'storm', category: 'set_19' },
      { id: 'short', label: 'short', category: 'set_19' },
      { id: 'port', label: 'port', category: 'set_19' },
      { id: 'north', label: 'north', category: 'set_19' },
      { id: 'more', label: 'more', category: 'set_19' },
    ]
  },
  {
    id: 'set_20',
    name: 'Set 20: oi / oy',
    skills: [
      { id: 'coin', label: 'coin', category: 'set_20' },
      { id: 'join', label: 'join', category: 'set_20' },
      { id: 'point', label: 'point', category: 'set_20' },
      { id: 'spoil', label: 'spoil', category: 'set_20' },
      { id: 'soil', label: 'soil', category: 'set_20' },
      { id: 'boil', label: 'boil', category: 'set_20' },
      { id: 'oil', label: 'oil', category: 'set_20' },
      { id: 'foil', label: 'foil', category: 'set_20' },
      { id: 'toilet', label: 'toilet', category: 'set_20' },
      { id: 'avoid', label: 'avoid', category: 'set_20' },
      { id: 'boy', label: 'boy', category: 'set_20' },
      { id: 'toy', label: 'toy', category: 'set_20' },
      { id: 'joy', label: 'joy', category: 'set_20' },
      { id: 'enjoy', label: 'enjoy', category: 'set_20' },
      { id: 'annoy', label: 'annoy', category: 'set_20' },
      { id: 'employ', label: 'employ', category: 'set_20' },
      { id: 'destroy', label: 'destroy', category: 'set_20' },
      { id: 'cowboy', label: 'cowboy', category: 'set_20' },
      { id: 'loyal', label: 'loyal', category: 'set_20' },
      { id: 'royal', label: 'royal', category: 'set_20' },
    ]
  },
  {
    id: 'set_21',
    name: 'Set 21: ow / ou',
    skills: [
      { id: 'cow', label: 'cow', category: 'set_21' },
      { id: 'now', label: 'now', category: 'set_21' },
      { id: 'how', label: 'how', category: 'set_21' },
      { id: 'town', label: 'town', category: 'set_21' },
      { id: 'down', label: 'down', category: 'set_21' },
      { id: 'clown', label: 'clown', category: 'set_21' },
      { id: 'brown', label: 'brown', category: 'set_21' },
      { id: 'frown', label: 'frown', category: 'set_21' },
      { id: 'crown', label: 'crown', category: 'set_21' },
      { id: 'owl', label: 'owl', category: 'set_21' },
      { id: 'out', label: 'out', category: 'set_21' },
      { id: 'about', label: 'about', category: 'set_21' },
      { id: 'shout', label: 'shout', category: 'set_21' },
      { id: 'cloud', label: 'cloud', category: 'set_21' },
      { id: 'found', label: 'found', category: 'set_21' },
      { id: 'sound', label: 'sound', category: 'set_21' },
      { id: 'ground', label: 'ground', category: 'set_21' },
      { id: 'round', label: 'round', category: 'set_21' },
      { id: 'mouth', label: 'mouth', category: 'set_21' },
      { id: 'south', label: 'south', category: 'set_21' },
    ]
  },
  {
    id: 'set_22',
    name: 'Set 22: ore / aw / au',
    skills: [
      { id: 'more', label: 'more', category: 'set_22' },
      { id: 'sore', label: 'sore', category: 'set_22' },
      { id: 'core', label: 'core', category: 'set_22' },
      { id: 'score', label: 'score', category: 'set_22' },
      { id: 'before', label: 'before', category: 'set_22' },
      { id: 'saw', label: 'saw', category: 'set_22' },
      { id: 'claw', label: 'claw', category: 'set_22' },
      { id: 'draw', label: 'draw', category: 'set_22' },
      { id: 'straw', label: 'straw', category: 'set_22' },
      { id: 'lawn', label: 'lawn', category: 'set_22' },
      { id: 'yawn', label: 'yawn', category: 'set_22' },
      { id: 'paw', label: 'paw', category: 'set_22' },
      { id: 'raw', label: 'raw', category: 'set_22' },
      { id: 'fault', label: 'fault', category: 'set_22' },
      { id: 'haunt', label: 'haunt', category: 'set_22' },
      { id: 'launch', label: 'launch', category: 'set_22' },
      { id: 'author', label: 'author', category: 'set_22' },
      { id: 'autumn', label: 'autumn', category: 'set_22' },
      { id: 'pause', label: 'pause', category: 'set_22' },
    ]
  },
  {
    id: 'set_23',
    name: 'Set 23: oo / ew / ue / u_e (Long U/OO)',
    skills: [
      { id: 'moon', label: 'moon', category: 'set_23' },
      { id: 'soon', label: 'soon', category: 'set_23' },
      { id: 'room', label: 'room', category: 'set_23' },
      { id: 'zoom', label: 'zoom', category: 'set_23' },
      { id: 'spoon', label: 'spoon', category: 'set_23' },
      { id: 'balloon', label: 'balloon', category: 'set_23' },
      { id: 'grew', label: 'grew', category: 'set_23' },
      { id: 'flew', label: 'flew', category: 'set_23' },
      { id: 'new', label: 'new', category: 'set_23' },
      { id: 'few', label: 'few', category: 'set_23' },
      { id: 'chew', label: 'chew', category: 'set_23' },
      { id: 'blue', label: 'blue', category: 'set_23' },
      { id: 'glue', label: 'glue', category: 'set_23' },
      { id: 'true', label: 'true', category: 'set_23' },
      { id: 'clue', label: 'clue', category: 'set_23' },
      { id: 'due', label: 'due', category: 'set_23' },
      { id: 'cube', label: 'cube', category: 'set_23' },
      { id: 'tube', label: 'tube', category: 'set_23' },
      { id: 'flute', label: 'flute', category: 'set_23' },
      { id: 'mule', label: 'mule', category: 'set_23' },
    ]
  },
  {
    id: 'set_24',
    name: 'Set 24: er / ir / ur (R-Controlled)',
    skills: [
      { id: 'her', label: 'her', category: 'set_24' },
      { id: 'term', label: 'term', category: 'set_24' },
      { id: 'tiger', label: 'tiger', category: 'set_24' },
      { id: 'ladder', label: 'ladder', category: 'set_24' },
      { id: 'sister', label: 'sister', category: 'set_24' },
      { id: 'bird', label: 'bird', category: 'set_24' },
      { id: 'third', label: 'third', category: 'set_24' },
      { id: 'shirt', label: 'shirt', category: 'set_24' },
      { id: 'girl', label: 'girl', category: 'set_24' },
      { id: 'swirl', label: 'swirl', category: 'set_24' },
      { id: 'fur', label: 'fur', category: 'set_24' },
      { id: 'turn', label: 'turn', category: 'set_24' },
      { id: 'burn', label: 'burn', category: 'set_24' },
      { id: 'curl', label: 'curl', category: 'set_24' },
      { id: 'surf', label: 'surf', category: 'set_24' },
      { id: 'hurt', label: 'hurt', category: 'set_24' },
      { id: 'nurse', label: 'nurse', category: 'set_24' },
      { id: 'burst', label: 'burst', category: 'set_24' },
      { id: 'church', label: 'church', category: 'set_24' },
      { id: 'purse', label: 'purse', category: 'set_24' },
    ]
  },
  {
    id: 'set_25',
    name: 'Set 25: tch / dge',
    skills: [
      { id: 'catch', label: 'catch', category: 'set_25' },
      { id: 'match', label: 'match', category: 'set_25' },
      { id: 'hatch', label: 'hatch', category: 'set_25' },
      { id: 'patch', label: 'patch', category: 'set_25' },
      { id: 'watch', label: 'watch', category: 'set_25' },
      { id: 'latch', label: 'latch', category: 'set_25' },
      { id: 'fetch', label: 'fetch', category: 'set_25' },
      { id: 'witch', label: 'witch', category: 'set_25' },
      { id: 'stitch', label: 'stitch', category: 'set_25' },
      { id: 'scratch', label: 'scratch', category: 'set_25' },
      { id: 'edge', label: 'edge', category: 'set_25' },
      { id: 'bridge', label: 'bridge', category: 'set_25' },
      { id: 'badge', label: 'badge', category: 'set_25' },
      { id: 'fudge', label: 'fudge', category: 'set_25' },
      { id: 'hedge', label: 'hedge', category: 'set_25' },
      { id: 'judge', label: 'judge', category: 'set_25' },
      { id: 'sledge', label: 'sledge', category: 'set_25' },
      { id: 'wedge', label: 'wedge', category: 'set_25' },
      { id: 'lodge', label: 'lodge', category: 'set_25' },
      { id: 'ridge', label: 'ridge', category: 'set_25' },
    ]
  },
  {
    id: 'set_26',
    name: 'Set 26: "c" as /s/ & "g" as /j/',
    skills: [
      { id: 'ice', label: 'ice', category: 'set_26' },
      { id: 'face', label: 'face', category: 'set_26' },
      { id: 'race', label: 'race', category: 'set_26' },
      { id: 'space', label: 'space', category: 'set_26' },
      { id: 'nice', label: 'nice', category: 'set_26' },
      { id: 'city', label: 'city', category: 'set_26' },
      { id: 'circle', label: 'circle', category: 'set_26' },
      { id: 'bicycle', label: 'bicycle', category: 'set_26' },
      { id: 'pencil', label: 'pencil', category: 'set_26' },
      { id: 'dance', label: 'dance', category: 'set_26' },
      { id: 'giant', label: 'giant', category: 'set_26' },
      { id: 'giraffe', label: 'giraffe', category: 'set_26' },
      { id: 'gem', label: 'gem', category: 'set_26' },
      { id: 'gentle', label: 'gentle', category: 'set_26' },
      { id: 'magic', label: 'magic', category: 'set_26' },
      { id: 'page', label: 'page', category: 'set_26' },
      { id: 'cage', label: 'cage', category: 'set_26' },
      { id: 'stage', label: 'stage', category: 'set_26' },
      { id: 'large', label: 'large', category: 'set_26' },
    ]
  },
  {
    id: 'set_27',
    name: 'Set 27: eigh / ea (Multiple Pronunciations)',
    skills: [
      { id: 'eight', label: 'eight', category: 'set_27' },
      { id: 'weight', label: 'weight', category: 'set_27' },
      { id: 'freight', label: 'freight', category: 'set_27' },
      { id: 'sleigh', label: 'sleigh', category: 'set_27' },
      { id: 'neighbor', label: 'neighbor', category: 'set_27' },
      { id: 'weigh', label: 'weigh', category: 'set_27' },
      { id: 'eighty', label: 'eighty', category: 'set_27' },
      { id: 'height', label: 'height', category: 'set_27' },
      { id: 'straight', label: 'straight', category: 'set_27' },
      { id: 'reindeer', label: 'reindeer', category: 'set_27' },
      { id: 'head', label: 'head', category: 'set_27' },
      { id: 'bread', label: 'bread', category: 'set_27' },
      { id: 'dead', label: 'dead', category: 'set_27' },
      { id: 'thread', label: 'thread', category: 'set_27' },
      { id: 'spread', label: 'spread', category: 'set_27' },
      { id: 'sweat', label: 'sweat', category: 'set_27' },
      { id: 'instead', label: 'instead', category: 'set_27' },
      { id: 'ready', label: 'ready', category: 'set_27' },
      { id: 'heavy', label: 'heavy', category: 'set_27' },
      { id: 'feather', label: 'feather', category: 'set_27' },
    ]
  },
  {
    id: 'set_28',
    name: 'Set 28: y / ey (Ending Sounds)',
    skills: [
      { id: 'happy', label: 'happy', category: 'set_28' },
      { id: 'sunny', label: 'sunny', category: 'set_28' },
      { id: 'funny', label: 'funny', category: 'set_28' },
      { id: 'puppy', label: 'puppy', category: 'set_28' },
      { id: 'party', label: 'party', category: 'set_28' },
      { id: 'jelly', label: 'jelly', category: 'set_28' },
      { id: 'cherry', label: 'cherry', category: 'set_28' },
      { id: 'bunny', label: 'bunny', category: 'set_28' },
      { id: 'windy', label: 'windy', category: 'set_28' },
      { id: 'lucky', label: 'lucky', category: 'set_28' },
      { id: 'monkey', label: 'monkey', category: 'set_28' },
      { id: 'donkey', label: 'donkey', category: 'set_28' },
      { id: 'turkey', label: 'turkey', category: 'set_28' },
      { id: 'valley', label: 'valley', category: 'set_28' },
      { id: 'alley', label: 'alley', category: 'set_28' },
      { id: 'chimney', label: 'chimney', category: 'set_28' },
      { id: 'honey', label: 'honey', category: 'set_28' },
      { id: 'money', label: 'money', category: 'set_28' },
      { id: 'key', label: 'key', category: 'set_28' },
      { id: 'journey', label: 'journey', category: 'set_28' },
    ]
  },
  {
    id: 'set_29',
    name: 'Set 29: ear / eer',
    skills: [
      { id: 'ear', label: 'ear', category: 'set_29' },
      { id: 'near', label: 'near', category: 'set_29' },
      { id: 'dear', label: 'dear', category: 'set_29' },
      { id: 'year', label: 'year', category: 'set_29' },
      { id: 'fear', label: 'fear', category: 'set_29' },
      { id: 'tear', label: 'tear', category: 'set_29' },
      { id: 'clear', label: 'clear', category: 'set_29' },
      { id: 'hear', label: 'hear', category: 'set_29' },
      { id: 'gear', label: 'gear', category: 'set_29' },
      { id: 'spear', label: 'spear', category: 'set_29' },
      { id: 'cheer', label: 'cheer', category: 'set_29' },
      { id: 'deer', label: 'deer', category: 'set_29' },
      { id: 'peer', label: 'peer', category: 'set_29' },
      { id: 'steer', label: 'steer', category: 'set_29' },
      { id: 'beer', label: 'beer', category: 'set_29' },
      { id: 'queer', label: 'queer', category: 'set_29' },
      { id: 'sneer', label: 'sneer', category: 'set_29' },
      { id: 'career', label: 'career', category: 'set_29' },
      { id: 'volunteer', label: 'volunteer', category: 'set_29' },
      { id: 'pioneer', label: 'pioneer', category: 'set_29' },
    ]
  },
  {
    id: 'set_30',
    name: 'Set 30: air / are',
    skills: [
      { id: 'air', label: 'air', category: 'set_30' },
      { id: 'fair', label: 'fair', category: 'set_30' },
      { id: 'hair', label: 'hair', category: 'set_30' },
      { id: 'pair', label: 'pair', category: 'set_30' },
      { id: 'chair', label: 'chair', category: 'set_30' },
      { id: 'stair', label: 'stair', category: 'set_30' },
      { id: 'flair', label: 'flair', category: 'set_30' },
      { id: 'repair', label: 'repair', category: 'set_30' },
      { id: 'despair', label: 'despair', category: 'set_30' },
      { id: 'airport', label: 'airport', category: 'set_30' },
      { id: 'care', label: 'care', category: 'set_30' },
      { id: 'share', label: 'share', category: 'set_30' },
      { id: 'spare', label: 'spare', category: 'set_30' },
      { id: 'square', label: 'square', category: 'set_30' },
      { id: 'scare', label: 'scare', category: 'set_30' },
      { id: 'bare', label: 'bare', category: 'set_30' },
      { id: 'rare', label: 'rare', category: 'set_30' },
      { id: 'stare', label: 'stare', category: 'set_30' },
      { id: 'glare', label: 'glare', category: 'set_30' },
      { id: 'compare', label: 'compare', category: 'set_30' },
    ]
  },
  {
    id: 'set_31',
    name: 'Set 31: ch as /k/ & /sh/',
    skills: [
      { id: 'school', label: 'school', category: 'set_31' },
      { id: 'echo', label: 'echo', category: 'set_31' },
      { id: 'anchor', label: 'anchor', category: 'set_31' },
      { id: 'chaos', label: 'chaos', category: 'set_31' },
      { id: 'chorus', label: 'chorus', category: 'set_31' },
      { id: 'character', label: 'character', category: 'set_31' },
      { id: 'mechanic', label: 'mechanic', category: 'set_31' },
      { id: 'stomach', label: 'stomach', category: 'set_31' },
      { id: 'architect', label: 'architect', category: 'set_31' },
      { id: 'scheme', label: 'scheme', category: 'set_31' },
      { id: 'chef', label: 'chef', category: 'set_31' },
      { id: 'machine', label: 'machine', category: 'set_31' },
      { id: 'brochure', label: 'brochure', category: 'set_31' },
      { id: 'chute', label: 'chute', category: 'set_31' },
      { id: 'charade', label: 'charade', category: 'set_31' },
      { id: 'parachute', label: 'parachute', category: 'set_31' },
      { id: 'moustache', label: 'moustache', category: 'set_31' },
      { id: 'chalet', label: 'chalet', category: 'set_31' },
      { id: 'champagne', label: 'champagne', category: 'set_31' },
      { id: 'cache', label: 'cache', category: 'set_31' },
    ]
  },
  {
    id: 'set_32',
    name: 'Set 32: kn / gn',
    skills: [
      { id: 'knee', label: 'knee', category: 'set_32' },
      { id: 'knew', label: 'knew', category: 'set_32' },
      { id: 'knife', label: 'knife', category: 'set_32' },
      { id: 'knock', label: 'knock', category: 'set_32' },
      { id: 'knit', label: 'knit', category: 'set_32' },
      { id: 'knob', label: 'knob', category: 'set_32' },
      { id: 'know', label: 'know', category: 'set_32' },
      { id: 'knight', label: 'knight', category: 'set_32' },
      { id: 'kneel', label: 'kneel', category: 'set_32' },
      { id: 'knuckle', label: 'knuckle', category: 'set_32' },
      { id: 'gnome', label: 'gnome', category: 'set_32' },
      { id: 'gnaw', label: 'gnaw', category: 'set_32' },
      { id: 'gnat', label: 'gnat', category: 'set_32' },
      { id: 'gnash', label: 'gnash', category: 'set_32' },
      { id: 'sign', label: 'sign', category: 'set_32' },
      { id: 'design', label: 'design', category: 'set_32' },
      { id: 'assign', label: 'assign', category: 'set_32' },
      { id: 'resign', label: 'resign', category: 'set_32' },
      { id: 'align', label: 'align', category: 'set_32' },
      { id: 'consign', label: 'consign', category: 'set_32' },
    ]
  },
  {
    id: 'set_33',
    name: 'Set 33: Schwa (Unstressed Vowels)',
    skills: [
      { id: 'banana', label: 'banana', category: 'set_33' },
      { id: 'animal', label: 'animal', category: 'set_33' },
      { id: 'pencil', label: 'pencil', category: 'set_33' },
      { id: 'hospital', label: 'hospital', category: 'set_33' },
      { id: 'family', label: 'family', category: 'set_33' },
      { id: 'camera', label: 'camera', category: 'set_33' },
      { id: 'problem', label: 'problem', category: 'set_33' },
      { id: 'button', label: 'button', category: 'set_33' },
      { id: 'wagon', label: 'wagon', category: 'set_33' },
      { id: 'salad', label: 'salad', category: 'set_33' },
      { id: 'apron', label: 'apron', category: 'set_33' },
      { id: 'pilot', label: 'pilot', category: 'set_33' },
      { id: 'doctor', label: 'doctor', category: 'set_33' },
      { id: 'actor', label: 'actor', category: 'set_33' },
      { id: 'editor', label: 'editor', category: 'set_33' },
      { id: 'colour', label: 'colour', category: 'set_33' },
      { id: 'teacher', label: 'teacher', category: 'set_33' },
      { id: 'dollar', label: 'dollar', category: 'set_33' },
      { id: 'sofa', label: 'sofa', category: 'set_33' },
      { id: 'about', label: 'about', category: 'set_33' },
    ]
  },
  {
    id: 'set_34',
    name: 'Set 34: wr / mb (Silent Letters)',
    skills: [
      { id: 'write', label: 'write', category: 'set_34' },
      { id: 'wrote', label: 'wrote', category: 'set_34' },
      { id: 'written', label: 'written', category: 'set_34' },
      { id: 'wrist', label: 'wrist', category: 'set_34' },
      { id: 'wrap', label: 'wrap', category: 'set_34' },
      { id: 'wrong', label: 'wrong', category: 'set_34' },
      { id: 'wreck', label: 'wreck', category: 'set_34' },
      { id: 'wring', label: 'wring', category: 'set_34' },
      { id: 'wrinkle', label: 'wrinkle', category: 'set_34' },
      { id: 'wren', label: 'wren', category: 'set_34' },
      { id: 'lamb', label: 'lamb', category: 'set_34' },
      { id: 'comb', label: 'comb', category: 'set_34' },
      { id: 'tomb', label: 'tomb', category: 'set_34' },
      { id: 'numb', label: 'numb', category: 'set_34' },
      { id: 'thumb', label: 'thumb', category: 'set_34' },
      { id: 'climb', label: 'climb', category: 'set_34' },
      { id: 'limb', label: 'limb', category: 'set_34' },
      { id: 'bomb', label: 'bomb', category: 'set_34' },
      { id: 'crumb', label: 'crumb', category: 'set_34' },
      { id: 'plumber', label: 'plumber', category: 'set_34' },
    ]
  },
  {
    id: 'set_35',
    name: 'Set 35: Final /LE/ Syllable',
    skills: [
      { id: 'candle', label: 'candle', category: 'set_35' },
      { id: 'handle', label: 'handle', category: 'set_35' },
      { id: 'bottle', label: 'bottle', category: 'set_35' },
      { id: 'little', label: 'little', category: 'set_35' },
      { id: 'middle', label: 'middle', category: 'set_35' },
      { id: 'puzzle', label: 'puzzle', category: 'set_35' },
      { id: 'apple', label: 'apple', category: 'set_35' },
      { id: 'table', label: 'table', category: 'set_35' },
      { id: 'simple', label: 'simple', category: 'set_35' },
      { id: 'people', label: 'people', category: 'set_35' },
      { id: 'purple', label: 'purple', category: 'set_35' },
      { id: 'turtle', label: 'turtle', category: 'set_35' },
      { id: 'circle', label: 'circle', category: 'set_35' },
      { id: 'giggle', label: 'giggle', category: 'set_35' },
      { id: 'bubble', label: 'bubble', category: 'set_35' },
      { id: 'rattle', label: 'rattle', category: 'set_35' },
      { id: 'tickle', label: 'tickle', category: 'set_35' },
      { id: 'angle', label: 'angle', category: 'set_35' },
      { id: 'fable', label: 'fable', category: 'set_35' },
      { id: 'title', label: 'title', category: 'set_35' },
    ]
  }
];

export const HFW_SETS: HFWSet[] = [
  {
    id: 'set1',
    name: 'Set 1',
    words: ['and', 'for', 'the', 'is', 'of', 'a', 'I', 'my', 'are', 'was']
  },
  {
    id: 'set2',
    name: 'Set 2',
    words: ['all', 'to', 'said', 'says', 'she', 'he', 'we', 'me', 'with', 'what', 'you', 'your']
  },
  {
    id: 'set3',
    name: 'Set 3',
    words: ["I'm", 'have', 'went', 'be', 'like', 'so', 'were', 'go', 'little', 'as', 'no', 'one']
  },
  {
    id: 'set4',
    name: 'Set 4',
    words: ['into', 'now', 'came', 'oh', 'about', 'there', 'their', 'these', 'people', 'put']
  }
];

// Helper to flatten skills for easy lookup
export const ALL_SKILLS = PHONICS_DATA.flatMap(c => c.skills);
